apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emp--dir-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-dir
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: AverageValue
          averageValue: 70m

