#SPDX-License-Identifier: MIT-0
---
# handlers file for app-deployment
- name: restart systemd
  service:
    daemon-reload: yes

- name: restart empdir service
  service:
    name: empdir
    state: restarted
