name: Multi region & Multi cluster Deployment
on:
    workflow_dispatch:
      inputs:
        actions:
          description: "Enter the action you need to do with terraform"
          type: choice
          options:
            - plan
            - apply
            - destroy
    # push:
    #     branches:
    #       - multi-region-eks
    #       - main
    #       - stage
env:
    PROJECT_NAME: ${{secrets.PROJECT_NAME}}
    ENVIRONMENT: ${{github.ref == 'refs/heads/main' && 'production' || 'stage'}}

jobs:
    Infrastructure-Creation:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./infrastructure

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: AWS configure
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-region: ${{secrets.AWS_REGION}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              id: init
              run: terraform init -backend-config="bucket=${{secrets.TF_STATE_BUCKET}}"

            - name: Terraform format
              id: fmt
              run: terraform fmt -check

            - name: Terraform validate
              run: terraform validate

            - name: Terraform workspace
              run: terraform workspace select ${{env.ENVIRONMENT}} || terraform workspace new ${{env.ENVIRONMENT}}

            - name: Terraform Plan
              if: github.event.inputs.actions == 'plan' || github.event.inputs.actions == 'apply'
              id: plan
              run: terraform plan -no-color -input=false -out planfile

            - name: Terraform Plan check
              if: github.event.inputs.actions == 'plan' || github.event.inputs.actions == 'apply' && steps.plan.outcome == 'failure'
              run: exit 1

            - name: Terraform apply
              if: github.event.inputs.actions == 'apply'
              run: terraform apply -no-color -auto-approve -input=false planfile

            - name: Terraform Destory
              if: github.event.inputs.actions == 'destroy'
              run: terraform destroy -auto-approve

    Multi-Cluster-Deployment:
        runs-on: ubuntu-latest
        needs: Infrastructure-Creation
        if: github.event.inputs.actions == 'apply'
        defaults:
          run:
            shell: bash
            working-directory: ./emp-dir-helm
        strategy:
          matrix:
            cluster:
                - name: employee-directory
                  region: ap-south-1
                - name: employee-directory
                  region: us-west-1
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: AWS configure
            uses: aws-actions/configure-aws-credentials@v4.1.0
            with:
              aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
              aws-region: ${{secrets.AWS_REGION}}
              aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

          - name: Update Kubeconfig
            run: aws eks update-kubeconfig --name ${{matrix.cluster.name}} --region ${{matrix.cluster.region}}

          - name: Setup Kubectl
            uses: azure/setup-kubectl@v4
            
          - name: Setup Helm
            uses: azure/setup-helm@v4.3.0

          - name: Deploy in EKS
            run: helm upgrade --install ${{matrix.cluster.name}} . --namespace ${{env.ENVIRONMENT}} --create-namespace
            
